- platform: LinkedIn
  date: 2025-05-05
  title: Grapevine Modeling Under Combined Abiotic Stress
  url: https://www.linkedin.com/posts/kidanemaryam_grapevine-model-combined-share-7409864896294612992-yPe6
  description: Shared an update on grapevine responses to combined stress, with emphasis on modeling, physiology, and stress-resilience traits.

  date: 2025-05-05
  title: Biological network analysis is insuring how plants are responding to environmental stress
  url: https://www.linkedin.com/posts/kidanemaryam_biological-network-plant-share-7436929863212752897-NEad?utm_source=share&utm_medium=member_desktop&rcm=ACoAAArOCOEBGmB8CmSseFv1O0E8sIhJvrViw_k
  description: Shared an update on grapevine responses to combined stress, with emphasis on modeling, physiology, and stress-resilience traits.
  


- platform: X
  date: 2025-05-05
  title: Grapevine Stress Physiology And Predictive Modeling
  url: https://x.com/reKidane/status/1919356057945534965
  description: Posted a research update related to grapevine stress physiology, combined abiotic stress, and data-driven crop resilience.


  date: 2025-05-05
  title: Our recent research paper  reveal a critical salinity threshold in plants. 
  url: https://x.com/reKidane/status/1919356051150799261?s=20
  description:  This finding is pivotal for enhancing crop resilience in saline environments.
